version: '3' # not realy needed

services:
  web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - redis
    volumes: # volume is not needed here
      - .:/app 

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data # I asked to add the mapped volume for Redis data persistence in the repository (should be a file mapped to the container)

volumes: 
  redis_data:
